[theme]
primaryColor = "#249D8F"
backgroundColor = "#141820"
secondaryBackgroundColor = "#1a2030"
textColor = "#FDF0D5"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
